categories:
  - title: '🚀 Enhancements'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bugfix'
  - title: '🧰 Maintenance'
    label:
      - 'chore'
      - 'documentation'
      - 'dependencies'
template: |
  If you installed xcodes with homebrew you can upgrade with `brew upgrade xcodesorg/made/xcodes`.

  ## Changes

  $CHANGES
