name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      env: 
        DEVELOPER_DIR: /Applications/Xcode_16.4.app
      run: swift test
